name: workshop_management_app
description: A Flutter application for managing a small workshop.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjusted based on typical Flutter project requirements

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0
  provider: ^6.0.0
  intl: ^0.17.0 # Ensure this is the version you intend, or use a more recent one like ^0.18.0 or ^0.19.0
  pdf: ^3.0.0 # Ensure this is the version you intend, or use a more recent one like ^3.10.0
  path_provider: ^2.0.0 # Or latest version
  permission_handler: ^10.0.0 # Or latest version
  path: ^1.8.0 # Added path package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 # Or a more recent version like ^3.0.0
  mockito: ^5.4.4 # Or latest version
  build_runner: ^2.4.8 # Or latest version
  sqflite_common_ffi: ^2.3.0 # Or latest

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An example of adding data from asset bundles is documented here:
  # https://flutter.dev/docs/development/ui/assets-and-images#resolution-aware

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
